docker:
  # Install docker image in ./docker
  image: docker:latest
  services:
    - docker:dind


test:

  before_script:
    - apk add --no-cache --upgrade bash

  stage: test
  script:
    - ./src/test/script/run_all_tests.sh
