# If mvn compil fails, reject the commit
on push:
  before_script:
    - apk add --no-cache --upgrade bash
    # Install dependencies (mvn)
    - apk add --no-cache --upgrade maven
  script:
    - mvn compile
  allow_failure: false

stages:
  - build
  - test
  - notify_discord

build:
  before_script:
    - apk add --no-cache --upgrade bash
    # Install dependencies (mvn)
    - apk add --no-cache --upgrade maven
  stage: build
  script:
    - mvn compile
  allow_failure: false
  when : always

# Unit test
test:
  stage: test
  script:
    - ./src/test/script/run_all_tests.sh
  when : on_success

# Notify discord
.notify_discord: &notify_discord
  before_script:
    - apk add --no-cache --upgrade bash
    - apk add --no-cache --upgrade curl
  stage: notify_discord

notify_discord_success:
    <<: *notify_discord
    when : on_success
    script:
      - 'curl -X POST -H "Content-Type: application/json" -d "{\"content\":\"Plus un push !\"}" https://discord.com/api/webhooks/1187702532554895431/CrsFIZMdfILQrGXoB09JTv9W5mHDKcst4aTX_B4Sim8PjFH97ImD8pfHB7IqZcT0sSo6'

notify_discord_failure:
    <<: *notify_discord
    when : on_failure
    needs:
      - test
    script:
      - 'curl -X POST -H "Content-Type: application/json" -d "{\"content\":\"Plus un push (par contre tout les tests ne passent pas) \"}" https://discord.com/api/webhooks/1187702532554895431/CrsFIZMdfILQrGXoB09JTv9W5mHDKcst4aTX_B4Sim8PjFH97ImD8pfHB7IqZcT0sSo6'

# if build fails, notify discord
notify_discord_build_failure:
    <<: *notify_discord
    script:
      - 'curl -X POST -H "Content-Type: application/json" -d "{\"content\":\"[Les gars ça compile pas](https://giphy.com/embed/kNA1sKSqxgFDq) \"}" https://discord.com/api/webhooks/1187702532554895431/CrsFIZMdfILQrGXoB09JTv9W5mHDKcst4aTX_B4Sim8PjFH97ImD8pfHB7IqZcT0sSo6'
    needs:
      - build