# If mvn compil fails, reject the commit
on push:
  script:
    - mvn compile

# Unit test
test:

  before_script:
    - apk add --no-cache --upgrade bash
    # Install dependencies (mvn)
    - apk add --no-cache --upgrade maven
    - mvn --version

  stage: test
  script:
    - ./src/test/script/run_all_tests.sh
