# Install docker in ./docker
default:
  image: ./docker/Dockerfile


test:

  before_script:
    - apk add --no-cache --upgrade bash
    - ./docker/run.sh

  stage: test
  script:
    - ./src/test/script/run_all_tests.sh
